######################################################################
# Automatically generated by qmake (3.1) Fri Oct 25 19:17:23 2019
######################################################################

TEMPLATE = app
TARGET = baldwin_veering
INCLUDEPATH += .


DEFINES += BRAIN_RQL

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/agent.hpp \
           src/ann.hpp \
           src/argparse.hh \
           src/constants.h \
           src/dq_rl_logic.hpp \
           src/field.hpp \
           src/genome.hpp \
           src/population.hpp \
           src/pq_rl_logic.hpp \
           src/rbm.hpp \
           src/rl_logic.hpp \
           src/rq_rl_logic.hpp \
           src/ParallelExtension/MPI_Control.h \
           src/ParallelExtension/MPI_DataExchange.h \
           src/ParallelExtension/MPI_DomainDec.h \
           src/ParallelExtension/MPI_Grouping.h
SOURCES += src/agent.cpp \
           src/dq_rl_logic.cpp \
           src/field.cpp \
           src/genome.cpp \
           src/main.cpp \
           src/parallel.cpp \
           src/population.cpp \
           src/population_io.cpp \
           src/pq_rl_logic.cpp \
           src/rbm.cpp \
           src/rl_logic.cpp \
           src/rq_rl_logic.cpp \
           src/test.cpp \
           src/ParallelExtension/MPI_Control.cpp \
           src/ParallelExtension/MPI_DataExchange.cpp \
           src/ParallelExtension/MPI_DomainDec.cpp \
           src/ParallelExtension/MPI_Grouping.cpp

INCLUDEPATH += $$PWD/../tiny-dnn

LIBS += -leigen

INCLUDEPATH += /usr/include/eigen3
