I_array="-DLEARN;-DSKILL_TO_SEE -DSKILL_TO_EAT;-DSKILL_TO_EAT;-DSKILL_TO_SEE;-DLEARN -DSKILL_TO_SEE -DSKILL_TO_EAT;-DLEARN -DSKILL_TO_EAT;-DLEARN -DSKILL_TO_SEE"
I_ENAMES="special;special_rl;special_drl"
I_EFLAG="-DBRAIN_QL;-DBRAIN_DEEP"
I_PNAMES="parameters.sh;parameters.sh;parameters_drl.sh"
